name: CICD_neto

on:
  push:
    branches:
      - for_cicd

  jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
        - name: Check repo
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
